#Requires -Version 7
<#
.SYNOPSIS
    Connects your GitHub repo to Azure for automatic deployments.
    Run this ONCE after your first deploy.

.DESCRIPTION
    This script:
      1. Creates an Azure Service Principal for GitHub Actions
      2. Grants it the right permissions on your resource group
      3. Adds all required secrets and variables to your GitHub repo
      4. Verifies the connection works

    After this runs, every push to 'main' will automatically
    build and deploy to Azure — no manual steps needed.

.EXAMPLE
    .\scripts\Setup-GitHubActions.ps1 -GitHubRepo "yourusername/mailguard"

.NOTES
    Requirements:
      - GitHub CLI (winget install GitHub.cli)
      - Azure CLI logged in
      - deployment-info.txt from your initial deploy
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string] $GitHubRepo,   # e.g. "yourusername/mailguard"

    [string] $DeploymentInfo = ""   # path to deployment-info.txt, auto-detected if empty
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Step { param($n, $msg) Write-Host "`nStep $n — $msg" -ForegroundColor Cyan }
function Write-Ok   { param($msg)     Write-Host "  ✅ $msg" -ForegroundColor Green }
function Write-Info { param($msg)     Write-Host "  ℹ️  $msg" -ForegroundColor Gray }
function Write-Fail { param($msg)     Write-Host "  ❌ $msg" -ForegroundColor Red; exit 1 }

Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════╗" -ForegroundColor Magenta
Write-Host "║      MailGuard — GitHub Actions Setup                 ║" -ForegroundColor Magenta
Write-Host "╚═══════════════════════════════════════════════════════╝" -ForegroundColor Magenta
Write-Host ""

# ── Step 1: Check tools ───────────────────────────────────────────────────────
Write-Step 1 "Checking required tools..."

if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-Host "  GitHub CLI not found. Installing..." -ForegroundColor Yellow
    winget install GitHub.cli
    Write-Host "  Please restart PowerShell and run this script again." -ForegroundColor Yellow
    exit 0
}
Write-Ok "GitHub CLI found"

if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
    Write-Fail "Azure CLI not found. Run: winget install Microsoft.AzureCLI"
}
Write-Ok "Azure CLI found"

# ── Step 2: Read deployment info ──────────────────────────────────────────────
Write-Step 2 "Reading deployment info..."

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot  = Split-Path -Parent $scriptDir

if (-not $DeploymentInfo) {
    $DeploymentInfo = Join-Path $repoRoot "deployment-info.txt"
}

if (-not (Test-Path $DeploymentInfo)) {
    Write-Fail "deployment-info.txt not found at '$DeploymentInfo'. Run deploy.ps1 first."
}

$info = Get-Content $DeploymentInfo | Where-Object { $_ -match ':' }
$parsed = @{}
foreach ($line in $info) {
    $parts = $line -split ':', 2
    if ($parts.Count -eq 2) {
        $parsed[$parts[0].Trim()] = $parts[1].Trim()
    }
}

$resourceGroup  = $parsed["Resource Group"]
$containerApp   = $parsed["Container App"]
$acrName        = ($parsed["Registry"] -split '\.')[0]
$subscriptionId = $parsed["Subscription"]

if (-not $resourceGroup -or -not $containerApp -or -not $acrName) {
    Write-Fail "Could not parse deployment-info.txt. Make sure it was generated by deploy.ps1."
}

Write-Ok "Resource Group : $resourceGroup"
Write-Ok "Container App  : $containerApp"
Write-Ok "Registry       : $acrName"
Write-Ok "Subscription   : $subscriptionId"

# ── Step 3: GitHub login ──────────────────────────────────────────────────────
Write-Step 3 "Checking GitHub login..."

$ghStatus = gh auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Info "Not logged into GitHub. Opening browser..."
    gh auth login
}
Write-Ok "GitHub authenticated"

# Verify repo exists and we have access
$repoCheck = gh repo view $GitHubRepo --json name 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Fail "Cannot access repo '$GitHubRepo'. Check the name and your permissions."
}
Write-Ok "Repo '$GitHubRepo' accessible"

# ── Step 4: Create Azure Service Principal ────────────────────────────────────
Write-Step 4 "Creating Azure Service Principal for GitHub Actions..."

$spName = "github-actions-mailguard"

# Check if already exists
$existing = az ad sp list --display-name $spName --query "[0].appId" -o tsv 2>$null
if ($existing) {
    Write-Info "Service principal already exists — rotating credentials..."
    $spCreds = az ad sp credential reset --id $existing --output json | ConvertFrom-Json
    $clientId = $spCreds.appId
    $clientSecret = $spCreds.password
    $tenantId = $spCreds.tenant
} else {
    Write-Info "Creating new service principal..."
    $spCreds = az ad sp create-for-rbac `
        --name $spName `
        --role Contributor `
        --scopes "/subscriptions/$subscriptionId/resourceGroups/$resourceGroup" `
        --output json | ConvertFrom-Json
    $clientId     = $spCreds.appId
    $clientSecret = $spCreds.password
    $tenantId     = $spCreds.tenant
}

# Also grant AcrPush role for the container registry
$acrId = (az acr show --name $acrName --query id -o tsv)
az role assignment create `
    --assignee $clientId `
    --role AcrPush `
    --scope $acrId `
    --output none 2>$null

Write-Ok "Service principal ready: $clientId"

# Build the AZURE_CREDENTIALS JSON that GitHub Actions expects
$azureCreds = @{
    clientId       = $clientId
    clientSecret   = $clientSecret
    subscriptionId = $subscriptionId
    tenantId       = $tenantId
} | ConvertTo-Json -Compress

# ── Step 5: Set GitHub secrets ────────────────────────────────────────────────
Write-Step 5 "Adding secrets and variables to GitHub repo..."

# Secrets (sensitive — encrypted by GitHub)
Write-Info "Setting AZURE_CREDENTIALS secret..."
$azureCreds | gh secret set AZURE_CREDENTIALS --repo $GitHubRepo

Write-Ok "Secret AZURE_CREDENTIALS set"

# Variables (non-sensitive — visible in workflow logs)
Write-Info "Setting repository variables..."
gh variable set ACR_NAME       --body $acrName       --repo $GitHubRepo
gh variable set CONTAINER_APP  --body $containerApp  --repo $GitHubRepo
gh variable set RESOURCE_GROUP --body $resourceGroup --repo $GitHubRepo

Write-Ok "Variables ACR_NAME, CONTAINER_APP, RESOURCE_GROUP set"

# ── Step 6: Create GitHub environment ─────────────────────────────────────────
Write-Step 6 "Configuring GitHub environment..."

# Create 'production' environment via API
$repoInfo = gh repo view $GitHubRepo --json owner,name | ConvertFrom-Json
$owner    = $repoInfo.owner.login
$repoName = $repoInfo.name

gh api --method PUT "repos/$owner/$repoName/environments/production" `
    --field wait_timer=0 `
    --silent 2>$null

Write-Ok "Production environment configured"

# ── Step 7: Test the connection ───────────────────────────────────────────────
Write-Step 7 "Verifying setup..."

# Trigger a test workflow run
Write-Info "Triggering a test workflow run..."
gh workflow run "Build & Deploy to Azure" --repo $GitHubRepo 2>$null

if ($LASTEXITCODE -eq 0) {
    Write-Ok "Workflow triggered successfully"
} else {
    Write-Info "Could not trigger workflow automatically (workflow may not be pushed yet)"
}

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║           ✅  GitHub Actions ready!                   ║" -ForegroundColor Green
Write-Host "╚═══════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "  Every push to 'main' will now automatically:" -ForegroundColor White
Write-Host "    1. Run tests" -ForegroundColor Gray
Write-Host "    2. Build and push the Docker image" -ForegroundColor Gray
Write-Host "    3. Deploy to Azure" -ForegroundColor Gray
Write-Host "    4. Health check the deployment" -ForegroundColor Gray
Write-Host ""
Write-Host "  Monitor deployments at:" -ForegroundColor White
Write-Host "  https://github.com/$GitHubRepo/actions" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Your deploy workflow:" -ForegroundColor White
Write-Host "    git add ." -ForegroundColor Gray
Write-Host "    git commit -m 'your change'" -ForegroundColor Gray
Write-Host "    git push" -ForegroundColor Gray
Write-Host "  ...and Azure updates itself in ~10 minutes." -ForegroundColor Gray
Write-Host ""
