name: Trigger auto deployment for mailguard-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mailguard-app-AutoDeployTrigger-2215e176-a3ae-46c8-a75b-4eeea86594dd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MAILGUARDAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MAILGUARDAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MAILGUARDAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: mailguardacr7842.azurecr.io
          registryUsername: ${{ secrets.MAILGUARDAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MAILGUARDAPP_REGISTRY_PASSWORD }}
          containerAppName: mailguard-app
          resourceGroup: mailguard-rg
          imageToBuild: mailguardacr7842.azurecr.io/mailguard-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


